include: package:broxus_flutter_analysis/analysis_options.yaml
linter:
  rules:
    avoid_final_parameters: false
analyzer:
  exclude:
    - lib/di/di.config.dart
    - lib/nekoton_repository.module.dart
